delete http://localhost:3001/api/persons/62a94dc3e5f31933f9e19fc6

###
get http://localhost:3001/api/persons/

###
get http://localhost:3001/api/persons/62a94dc3e5f31933f9e19fc6

###
post http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Martin Cooper",
    "number": "534-9984-382"
}